### ISSUE TITLE
Failing purges with fastly-ruby v1.1.5

### ISSUE THREAD

**Issue by mmay** [fastly/fastly-rails#35]
Changes introduced to purging in fastly-ruby v1.1.5 do not play nice with fastly-rails v0.2.0.
Reproduced on ruby 2.1.0

Note v0.2.0  bumps the fastly-ruby dep to 1.1.4.

stack trace

```
Fastly::Error: Bad Request 
from /app/vendor/bundle/ruby/2.1.0/gems/fastly-1.1.5/lib/fastly/client.rb:95:in `post_and_put' 
from /app/vendor/bundle/ruby/2.1.0/gems/fastly-1.1.5/lib/fastly/client.rb:74:in `post' 
from /app/vendor/bundle/ruby/2.1.0/gems/fastly-rails-0.2.0/lib/fastly-rails/client.rb:12:in `purge_by_key'
from /app/vendor/bundle/ruby/2.1.0/gems/fastly-rails-0.2.0/lib/fastly-rails/active_record/surrogate_key.rb:33:in `purge'
```

**Comment by amyrlam** [comment]
From Tyler re: https://fastly.zendesk.com/agent/tickets/9591

> I am providing the api_key, user, password, service_id and max_age.

> FastlyRails.configure do |c| 
c.api_key = ENV['FASTLY_API_KEY'] 
c.user = ENV['FASTLY_USER'] 
c.password = ENV['FASTLY_PASSWORD'] 
c.service_id = ENV['FASTLY_SERVICE_ID'] 
c.max_age = 3600 
end
