### ISSUE TITLE
Does not work with rails-api

### ISSUE THREAD

**Issue by gingermusketeer** [fastly/fastly-rails#38]
Was not able to workout why this was not working in a rails-api app. turns out that it is because the base controller is `ActionController::API` not `ActionController`.

This means that all the controller methods this gem provides are not available

**Comment by jfranz** [comment]
To get this working as expected you need to include the FastlyRails controller modules in your app. The best place for this is usually in your `ApplicationController`.

```ruby
class ApplicationController < ActionController::API
  include FastlyRails::CacheControlHeaders
  include FastlyRails::SurrogateKeyHeaders
  ...
```

**Comment by gingermusketeer** [comment]
Yea. Be good if that was added to the documentation
