### ISSUE TITLE
FastlyRails shouldn't raise error when api key isn't set

### ISSUE THREAD

**Issue by herrstucki** [fastly/fastly-rails#44]
Currently, an error is raised when the API key isn't defined. This is pretty annoying during development because I obviously don't want my local development app to issue a real purge request.

Setting a dummy API key also doesn't help, because then Fastly throws an `Unauthorized` error.

**Comment by gingermusketeer** [comment]
@herrstucki This PR addressed that issue https://github.com/fastly/fastly-rails/pull/39

**Comment by thiagofigueiro** [comment]
@gingermusketeer #39 was finally merged! :+1:

**Comment by herrstucki** [comment]
Nice, thanks!
