### ISSUE TITLE
purging_enabled isn't supported in gem version 0.3.0

### ISSUE THREAD

**Issue by blarralde** [fastly/fastly-rails#46]
In the README you say to configure `purging_enabled` but it hasn't been added into version 0.3.0. Might want to either update the gem or specify to use the github repo as a source in the README.

**Comment by ehoch** [comment]
+1

**Comment by set5think** [comment]
Sorry about the confusion; we'll bump the version and release, so it doesn't cause confusion.

**Comment by set5think** [comment]
fastly-rails 0.4.0 released.  The README and Changelog has also been updated.
