### ISSUE TITLE
Enable use of current version of mime-types

### ISSUE THREAD

**Issue by david-a-wheeler** [fastly/fastly-rails#52]
fastly-rails version 0.5.0 requires "mime-types (>= 1.16, < 3)", but the current version of mime-types is 3.0.  Please make it possible to use the current version of mime-types.

Thanks!

**Comment by thommahoney** [comment]
@david-a-wheeler Thanks for raising awareness of this issue. Let's move the discussion to here: https://github.com/fastly/fastly-rails/pull/53
