### ISSUE TITLE
purging_enabled not considered

### ISSUE THREAD

**Issue by cthorner** [fastly/fastly-rails#59]
It looks like the purging_enabled flag is ignored. I'm still getting api requests to Fastly when setting this to true in the configuration.

Looking at the code I would expect a guard statement around this line:

https://github.com/fastly/fastly-rails/blob/8245aa86030a8cd46896a804adf35d2b450f9597/lib/fastly-rails/client.rb#L12

but maybe I'm missing something.

**Comment by thommahoney** [comment]
@cthorner does this line do what you're expecting? https://github.com/fastly/fastly-rails/blob/5a1b6aedd05354ccaed9a2105a659b5a75bf9292/lib/fastly-rails.rb#L26

**Comment by thommahoney** [comment]
> when setting this to true

@cthorner Try setting the value to `false` :)

**Comment by cthorner** [comment]
Ha! That would do the trick wouldn't it. :)
