### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by gja** [fastly/fastly-rails#64]
Currently, fastly-rails does not support Rails 5 due to being locked to `railtie < 5` in the gemspec. Adding fastly-rails to a rails project silently resolves to a really old version, `fastly-rails (0.4.1)`, the last version before the lock on railtie was added.

This seems to work fine in newer versions of rails, would it be possible to remove the dependency on railtie version, and mimetype?

**Comment by segantii-alex-falkowski** [comment]
When will this be resolved?
