### ISSUE TITLE
Have different configuration for a particular controller?

### ISSUE THREAD

**Issue by StarWar** [fastly/fastly-rails#74]
I have following default configuration in my initializer directory. I want to have different configurations for a particular controller. What should I do? It's not mentioned in the readme.
```
# frozen_string_literal: true
FastlyRails.configure do |c|
  c.api_key = ENV['FASTLY_API_KEY'] # Fastly api key, required
  c.max_age = 300                  # time in seconds, optional, defaults to 2592000 (30 days)
  c.stale_while_revalidate = 300   # time in seconds, optional, defaults to nil
  c.stale_if_error = 300           # time in seconds, optional, defaults to nil
  c.service_id = ENV['FASTLY_SERVICE_ID'] # The Fastly service you will be using, required
  c.purging_enabled = !Rails.env.development? # No need to configure a client locally (AVAILABLE ONLY AS OF 0.4.0)
end
```

**Comment by lanej** [comment]
@StarWar what particular aspect of the configuration are you looking to override for a particular controller?

**Comment by StarWar** [comment]
@lanej I want change max_age and stale_while_revalidate and stale_if_error options for some controllers.

**Comment by lanej** [comment]
You can pass those relevant options to `set_cache_control_headers` in your respective controller.  See https://github.com/fastly/fastly-rails/blob/c438461/lib/fastly-rails/action_controller/cache_control_headers.rb#L12

**Comment by StarWar** [comment]
@lanej Thanks, I've done that.
